

const data = {
  products: [
    {
      name: 'Anillo corazón Reborde',
      slug: 'anillo-corazon-reborde',
      category: 'Mujeres',
      image: 'https://i.ibb.co/WvBRFZd/IMG-6751.jpg',
      price: 3590000,
      brand: 'Destacados',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Anillo elaborado en oro 18K con incrustaciones en circón natural.',
    },
    {
      name: 'Anillo Corazón Pendulo',
      slug: 'anillo-corazon-pendulo',
      category: 'Mujeres',
      image: 'https://i.ibb.co/t371LTD/IMG-5610-IMG-5615.png',
      price: 3490000,
      brand: 'Destacados',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Anillo elaborado en oro 18K con incrustaciones en circón natural.',
    },
    {
      name: 'Anillo Ancho',
      slug: 'anillo-ancho',
      category: 'Mujeres',
      image: 'https://i.ibb.co/M1KJS3g/IMG-5619-IMG-5620-IMG-5621.png',
      price: 3790000,
      brand: 'Destacados',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Anillo elaborado en oro 18K con incrustaciones en circón natural.',
    },
    {
      name: 'Anillo Reborde',
      slug: 'anillo-reborde',
      category: 'Mujeres',
      image: 'https://i.ibb.co/Mp4mbbg/IMG-5587.jpg',
      price: 0,
      brand: 'Destacados',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Anillo elaborado en oro 18K con incrustaciones en circón natural.',
    },
    {
      name: 'Dije Corazón Reborde',
      slug: 'dije-corazon-reborde',
      category: 'Mujeres',
      image: 'https://i.ibb.co/kBLpLDB/20210222-160614.jpg',
      price: 2290000,
      brand: 'Destacados',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Dije elaborado en oro 18K con incrustaciones en circón natural.',
    },
    {
      name: 'Dije Fe',
      slug: 'dije-fe',
      category: 'Mujeres',
      image: 'https://i.ibb.co/r76GXsw/IMG-5154-IMG-8130-IMG-023134-IMG-7885-IMG-8198.png',
      price: 3590000,
      brand: 'Destacados',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Dije elaborado en oro 18K con turmalinas.',
    },
  ],
};

export default data;